### ISSUE TITLE
Update HDF5DataStore to support writing data into different file groups

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#23]
This task will involve modifying both the HDF5DataStore constructor and its write() method.

The goal is to add support for storage of data fragments in

1. one big file (e.g. a file with a name like demo.hdf5)

1. files which have all of the data from each event grouped together, but different events are stored in different files (e.g. files with names like demo_event<EventID>.hdf5)

1. files which have one fragment per file (e.g. files with names like demo_event<EventID>_geo<GeoLoc>.hdf5

Within the HDF5 files, we agreed to store the data in an HDF5 Group/DataSet structure that has top-level groups named by the event number and DataSets named by the geographic location.  So, for example, if we have an event-based file grouping, a file with 3 events (numbered 1-3) and 4 geographic locations per event (numbered 1-4), 

- there would be three top-level HDF5 Groups in the file, with names "1", "2", and "3", and each Group would have four DataSets, named "1", "2", "3", "4".

**Comment by adam-abed-abud** [comment]
Some issues encountered in the implementation. 

The HighFive createDataSet method does not accept a void as a data type. Therefore I switched back from void to char. 

Another issue encountered is the protection against creating twice the same HDF5 group. The fix for this problem is to create the HDF5 groups in the setup method of the HDF5DataStore and then retrieving them in the write method. I also used the "isValid()" method to check that the group is ready to be used for writing the data inside.

**Comment by bieryAtFnal** [comment]
I really would like us to avoid the use of a setup method for anything seen by user code.  As we discussed in our daily meeting, the user code should be as simple as
* loop
  * create fragment
  * write fragment

I recognize that this means that this means that the `write()` method will need to check if a given Group has already been created (and create it if needed).

**Comment by adam-abed-abud** [comment]
You are right, I put it there because it was easier at first.
Now everything is in the `write()` method.

**Comment by bieryAtFnal** [comment]
Just an update on this Issue...

As part of Pull Request #29, we discussed the progress that has been made in updating the `write()` method and merged the modified code into the `develop` branch.  The BinaryWriter demo that Adam created as part of this work can write a configurable number of HDF5 files (one event per file) with a configurable number of geoLocation-specific data blocks (i.e. fragments) within each file.
