### ISSUE TITLE
Investigate HDF5 files with no DataSets from SimpleDiskWriter

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#31]
This issue was noticed after the merge of Pull Request #29 into the _develop_ branch.

**Comment by bieryAtFnal** [comment]
The problem was caused by a simple bug in HDF5DataStore::write().  When a new group needed to be created, that was done (the group was created), but the code to actually write the data into the DataSet was in a different 'else' block.

This problem manifested itself as empty DataSets in demo.hdf5 when running the SimpleDiskWriter.
I believe that it also showed up in the BinaryWriter tests, and it was the reason that we only got 9 fragments per event instead of the requested 10.

I'll create a Pull Request for this fix.

**Comment by bieryAtFnal** [comment]
I should have said that a proposed fix is on the _feature/Issue31_MissingData_ branch

**Comment by adam-abed-abud** [comment]
Nice, good job. Two fixes with one patch!
