### ISSUE TITLE
We should create new ERS Issues for exceptions in HDF5DataStore

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#34]
I noticed that in our work on the HDF5DataStore `write()` and `read()` methods, we make use of ERS Issues that are defined in the DAQModule header files that are in the `src` subdirectory.

This is problematic because it requires the DAQModule header file to be included before the HDF5DataStore header file in order for the code to compile.

Also, my sense is that it would be good for us to create new ERS Issues in the HDF5DataStore header file that are tailored to the types of exceptional conditions that we expect in the HDF5DataStore code.

**Comment by bieryAtFnal** [comment]
Here is some example code based on the HDF5DataStore.hpp file that is currently on the `develop` branch:

```
--- a/include/ddpdemo/HDF5DataStore.hpp
+++ b/include/ddpdemo/HDF5DataStore.hpp
@@ -21,11 +21,16 @@
 
 #include "highfive/H5File.hpp"
 
-
 namespace dunedaq {
-namespace ddpdemo {
 
+ERS_DECLARE_ISSUE_BASE(ddpdemo,
+                       InvalidGroupError,
+                       appfwk::GeneralDAQModuleIssue,
+                       "The HDF5 Group associated with name \"" << groupName << "\" is not valid. (file = " << filename << ")
+                       ((std::string)name),
+                       ((std::string)groupName)((std::string)filename))
 
+namespace ddpdemo {
 
 class HDF5DataStore : public DataStore {
 
@@ -61,7 +66,7 @@ public:
     }
     HighFive::Group theGroup = filePtr->getGroup(datagroup_name);
     if (!theGroup.isValid()) {
-      throw InvalidDataWriterError(ERS_HERE, get_name());
+      throw InvalidGroupError(ERS_HERE, get_name(), datagroup_name, filePtr->getName());
     } else {
       const std::string dataset_name = std::to_string(dataBlock.data_key.getGeoLocation());
       HighFive::DataSpace theDataSpace = HighFive::DataSpace({ dataBlock.data_size, 1 });
```

**Comment by adam-abed-abud** [comment]
Hi Kurt,
 
I added the ERS message to the HDF5 writer application without using the Binary writer.

**Comment by carloschavez** [comment]
Hi Kurt, 
In feature/Issue26_DataStore_Reader branch I have created a new ERS Issue  and removed the one defined in DAQModule header files.
I also know using your KeyTranslator function in HDF5DataReader.hpp
