### ISSUE TITLE
Create a container class for holding parameter values that identify data (e.g. StorageKey)

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#4]
This container class will give us a way to group all of the parameters that identify a given block of data.  One can imagine that these parameters will be used to group and/or identify the data when it is stored in a particular storage medium.

**Comment by bieryAtFnal** [comment]
This task will involve
- documenting what sorts of information we might need to identify a block of data (Adam already mentioned EventID, DetectorID, and ComponentID) [please include that documentation, or at least a pointer to that documentation, in this Issue]
- deciding which ones of those we should implement first
- designing the C++ container class that will hold these parameters (private data members?  method signatures? const-ness?) [it would be fine to keep this simple, for now]
- implementing this class
- creating some unit tests that verify the correct operation of the class

**Comment by bieryAtFnal** [comment]
As I mentioned earlier, we could keep the first implementation of this class quite simple.  It could be a simple C++ struct that has one or two data members.  For example, the two data members could be run number and trigger record number.

The header file could look like the following:
```
struct StorageKey
{
public:
  uint32_t run;
  uint32_t record_identifier;  // trigger number or timeslice ID
};
```
Or, we could go ahead and invest the effort to make the data members private, provide accessor methods, think about efficient passing of data into the settors (const reference), etc.

It would likely have Doxygen comments, etc. like [https://github.com/DUNE-DAQ/appfwk/blob/develop/include/appfwk/Logger.hpp](https://github.com/DUNE-DAQ/appfwk/blob/develop/include/appfwk/Logger.hpp)

We would place the header file in the include/ddpdemo directory, and we could include it in src/SimpleDataWriter.cpp.

We could write some simple unit tests in the unittest subdirectory.  At first, these could just set the run number and trigger record number values in the struct and verify that we get the same ones back out.  See the unit tests [here](https://github.com/DUNE-DAQ/appfwk/tree/develop/unittest) for examples.

**Comment by adam-abed-abud** [comment]
Writing a StorageKey class. The structure is organized according to the following parameters:
-- Event ID
-- Detector ID
-- Geographical location
