### ISSUE TITLE
Decide on which HDF5 library to use and add it to the build infrastructure for this repo

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#6]

**Comment by bieryAtFnal** [comment]
We currently don't have a UPS product for the HighFive library.  We should talk with Software Coordination folks (Pengfei, John Freeman, Alessadro) about whether it would be possible to get one, or whether we should go with a library that is available from SciSoft (for now).

**Comment by dingp** [comment]
HighFive is a header only library. I should be able to create a UPS product for it quickly. Let me know if you want to try other HDF5 libraries. I'll make the UPS products quickly.

If we later decided on one HDF5 library, we can ask SciSoft to take over making the UPS product.

**Comment by bieryAtFnal** [comment]
@dingp Pengfei, it would be helpful to have a HighFive UPS product.  Thank you for offering to help with that.  My understanding is that the SciSoft team would rather not take on another HDF5 library at this point in time, but if you are willing to create one and make it available on cvmfs now, then we can make use of that version in the short term.  
Thanks,
Kurt

**Comment by bieryAtFnal** [comment]
It looks like we can use the model of downloading a copy of HighFive before a UPS package is available.  This can be done with a CMakeLists.txt file like the following:

```
cmake_minimum_required(VERSION 3.12)
project(ddpdemo VERSION 0.1.0)

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../daq-buildtools/cmake ${CMAKE_MODULE_PATH})
include(DAQ)

daq_setup_environment()

# 08-Sep-2020, KAB: the inclusion of the appfwk package brings in several other packages,
# including ERS, TRACE, and Boost
find_package(appfwk REQUIRED) 

# temporary way to get HighFive library
if( NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/HighFive )
    message("Cloning HighFive into ${CMAKE_CURRENT_BINARY_DIR}/HighFive")
    execute_process(COMMAND git clone https://github.com/BlueBrain/HighFive.git WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
endif()
include_directories(${CMAKE_CURRENT_BINARY_DIR}/HighFive/include)

##############################################################################
daq_point_build_to( src )

add_library(ddpdemo_SimpleDiskWriter_duneDAQModule src/SimpleDiskWriter.cpp)
target_link_libraries(ddpdemo_SimpleDiskWriter_duneDAQModule appfwk::appfwk)

##############################################################################
daq_point_build_to( test )

file(COPY test/disk_writer_demo.json DESTINATION test)

daq_install(TARGETS ddpdemo_SimpleDiskWriter_duneDAQModule )

```

**Comment by dingp** [comment]
I’ve pushed `highfive v2_2_2 -q e19:prof|debug`  together with the latest HDF5  to cvmfs.
```
[root@e2cf1316d3b2 highfive]# ups list -aK+ highfive
"highfive" "v2_2_2" "Linux64bit+3.10-2.17" "e19:prof" ""
"highfive" "v2_2_2" "Linux64bit+3.10-2.17" "debug:e19" ""
[root@e2cf1316d3b2 highfive]# ups list -aK+ hdf5
"hdf5" "v1_12_0a" "Linux64bit+3.10-2.17" "e19:prof" ""
"hdf5" "v1_12_0a" "Linux64bit+3.10-2.17" "debug:e19" ""
```

Please give it a try, especially with find_package(HighFive) in cmake. If it’s not working as expected, I may need to change the path when setting CMAKE_PREFIX_PATH in UPS table file. (edited) 

I made `highfive v2_2_0` dependent on `boost v1_70_0` and `hdf5 v1_12_0a`. Let me know if there’s a conflict. These dependencies worked fine when building the test code in highfive package.

```highfive v2_2_2 -f Linux64bit+3.10-2.17 -z /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products -q e19:prof
|__boost v1_70_0 -f Linux64bit+3.10-2.17 -z /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products -q e19:prof
|  |__gcc v8_2_0 -f Linux64bit+3.10-2.17 -z /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products
|__hdf5 v1_12_0a -f Linux64bit+3.10-2.17 -z /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products -q e19:prof```

**Comment by bieryAtFnal** [comment]
An update on this issue:

- Pengfei has created a UPS product for HighFive and made it available in /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev (Version=v2_2_2	Qualifiers="e19:prof")
- To make use of this, we need to add the following lines to the setup_build_environment script that gets created when we first set up a software development area
  - line 8: `. /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/setup1`
  - ~line 30:  `setup highfive v2_2_2 -q e19:prof`
- There is code on the _test/FirstHighFiveUse_ branch in the _ddpdemo_ repo that has a few simple HighFive statements included.  And, this branch has the changes to the CMakeLists.txt file that are needed.

**Comment by bieryAtFnal** [comment]
We are moving forward with the HighFive library.  Adam will be making use of it in his work on the HDF5DataStore class (Issue #12).

**Comment by bieryAtFnal** [comment]
We'll go ahead and close this task.
In the future, It might be nice to talk with SW Coordination folks to see if we can get the products_dev UPS software area automatically added to the setup_build_environment script.
